version: '3'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_PASSWORD: example
